### PR TITLE
Translated into Ukrainian

### PR DESCRIPTION
**Pull request by Starik1500**
I translated all the words that were available for translation into Ukrainian. But I still need to see how it will look in the application itself in order to finally approve the translation.

### CODE REVIEW

**Comment by dpaulino** [comment]
Thank you for the translations! I can merge this and submit an update to internal beta with your changes. You're part of the internal beta right? If so, you'd be able to test the changes before the broader public sees it. 

How does that sound? If that's good to you, we can merge this and I can deploy the update

**Comment by Starik1500** [comment]
> Thank you for the translations! I can merge this and submit an update to internal beta with your changes. You're part of the internal beta right? If so, you'd be able to test the changes before the broader public sees it.
> 
> How does that sound? If that's good to you, we can merge this and I can deploy the update

I don't know how it would be better, I translated it according to the context, but firstly, editing a raw file is different, I would like to see how it would look in the application, since the incorrect tense or case may appear there. Apparently, if we merge it, it will only be for the internal version for now, today I literally filled out the application + at the same time I think I will go over the grammar, I tried according to all the rules, but I still want to talk to other people how it would be better for them.

**Comment by dpaulino** [comment]
@Starik1500 I'm going to merge this and deploy an internal update. You can test the UI in ukrainian and then you can make additional updates after you do some testing.

**Comment by dpaulino** [comment]
The update is available to test. Please head to the Microsoft Store and get the latest internal beta update for beeskie, which is v0.6.16

**Comment by Starik1500** [comment]
Hi, I updated to 0.6.16, but I don't see interface language different from English, I have a pc with Ukrainian language and region, but English in Beesky. You can tell how to change, or it would be synchronization with language setting on pc?

**Comment by dpaulino** [comment]
Let me test it out myself.

**Comment by dpaulino** [comment]
@Starik1500 it's working for me

image


Here are my windows settings. Notice that UK is on the top for me and then I relaunched beeskie.

image

**Comment by dpaulino** [comment]
@Starik1500 if it's still not working for you, try uninstalling beeskie and reinstalling

**Comment by Starik1500** [comment]
Thank you, I didn't see that English set up first))

**Comment by dpaulino** [comment]
Great! If you want to make further improvements to your translations, feel free to create a new pull request to edit the file!

By the way, if you'd like to also provide translations to the Ukrainian Store page for Beeskie, just send me your translations here and I will update the store page. Here's how the page currently looks in Ukrainian: https://apps.microsoft.com/detail/9pcgnr7qhqgp?hl=uk-uk&gl=Uk

**Comment by Starik1500** [comment]
Yes, I have already tested and added a little editing. Translation of the text to the store, send it to your email?

**Comment by dpaulino** [comment]
Yep email sounds good

**Pull request merged**
